### ISSUE TITLE
OMERO.server doesn't work with dynamic volumes

### ISSUE THREAD

**Issue by manics** [manics/kubernetes-omero#1]
Permissions for Kubernetes dynamic volumes are often managed using group memberships. This causes OMERO.server to fail:
```
bash-4.2$ id
uid=1000(omero-server) gid=997(omero-server) groups=997(omero-server),2000
bash-4.2$ ls -ld /OMERO
drwxrwsr-x 3 root 2000 4096 Oct  7 20:51 /OMERO
```
The container is run with `securityContext.fsGroup: 2000` which matches the group of `/OMERO` but OMERO.server fails because the volume is owned by root: https://github.com/openmicroscopy/openmicroscopy/blob/v5.4.8/components/tools/OmeroPy/src/omero/plugins/admin.py#L1519-L1520
```
            msg += "FATAL: OMERO directory which needs to be writeable"\
                " belongs to root: %s\n" % filepath
```

**Comment by joshmoore** [comment]
https://github.com/ome/omero-py/pull/208 merged but not yet released.

**Comment by manics** [comment]
This should be included in https://github.com/manics/kubernetes-omero/pull/21
