### ISSUE TITLE
Unable to access omero-web pod as root user

### ISSUE THREAD

**Issue by shodzic10** [manics/kubernetes-omero#46]
When I try to access omero-web pod as a root user with "sudo" command, I am not able to do it. I get three chances to enter correct password for sudo user. We cannot use root user privileges because we don't know root user password. How can we enable root access or at least change root user password?

**Comment by manics** [comment]
This chart doesn't provide the OMERO.web Docker images, it just uses the ones built by https://github.com/ome/omero-web-docker so if you want to enable sudo you'll have to modify the image yourself to enable it. Hope that helps!
